### PR TITLE
Clean up after failed rebase.

### PR DESCRIPTION
**Pull request by hughsaunders**
Otherwise merge will also fail.

Related rcbops/u-suk-dev#223

### CODE REVIEW

**Comment by evrardjp** [comment]
Looks good, waiting for jenkins tests to pass.

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_aio

**Comment by hughsaunders** [comment]
recheck_upgrade

**Comment by hughsaunders** [comment]
recheck_upgrade

**Comment by hughsaunders** [comment]
recheck_aio

**Comment by evrardjp** [comment]
recheck_all -- E: Failed to fetch http://mirror.rackspace.com/ubuntu/pool/main/liba/libarchive/libarchive13_3.1.2-7ubuntu2.3_amd64.deb  404  Not Found

**Comment by hughsaunders** [comment]
recheck_all failed on apt again

**Comment by hughsaunders** [comment]
failed on hash sum mismatch installing hwraid packages

```
msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'megacli' 'lsiutil'' failed: E: Failed to fetch http://hwraid.le-vert.net/ubuntu/pool-trusty/lsiutil_1.60-2_amd64.deb  Hash Sum mismatch
```

recheck_all

**Comment by evrardjp** [comment]
recheck_upgrade

**Comment by hughsaunders** [comment]
failed on github auth related stack trace, have updated the github auth plugin. 

recheck_upgrade

**Comment by evrardjp** [comment]
Ready to merge, let's merge this to go further with the rcbops/rpc-openstack#1224

**Pull request merged**
