### PR TITLE
[WIP] Ensure resources survive an upgrade.

### PR DESCRIPTION
**Pull request by hughsaunders**
This is a basic implementation of a check for resource status after an
upgrade.

A pair of instances are created before an upgrade,
then checked for existence and reachability after the upgrade.

Future improvement would be to measure the downtime of these instances
during the upgrade (using something like downtimer).

Connects rcbops/u-suk-dev#230

### CODE REVIEW

**Comment by hughsaunders** [comment]
Test job: http://jenkins.propter.net/user/hughsaunders/my-views/view/All/job/JJB-RPC-AIO_mitaka-swift/1018/

**Comment by hughsaunders** [comment]
http://jenkins.propter.net/user/hughsaunders/my-views/view/All/job/JJB-RPC-AIO_mitaka-swift/1020/

**Comment by hughsaunders** [comment]
Upgrade persistent resources check passed, but failed on second tempest. Next attempt: http://jenkins.propter.net/user/hughsaunders/my-views/view/All/job/JJB-RPC-AIO_mitaka-swift/1025/

**Comment by hughsaunders** [comment]
Rebased, next test job: http://jenkins.propter.net/user/hughsaunders/my-views/view/All/job/JJB-RPC-AIO_mitaka-swift/1030/

**Comment by hughsaunders** [comment]
Rebased but can't be retested until https://github.com/rcbops/rpc-openstack/pull/1658 merges

**Comment by hughsaunders** [comment]
test build failed on tempest, looks like it couldn't authenticate via private key to the test instance. http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-swift-periodic/19/ 

Next build: http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-swift-periodic/23/

**Comment by hughsaunders** [comment]
Last build failed on waiting for elasticsearch to start:
```
03:46:16.908 TASK: [elasticsearch | Wait for ElasticSearch port] *************************** 
03:46:16.908 failed: [jramsp-23-3467_elasticsearch_container-db7b6355] => {"elapsed": 300, "failed": true}
03:46:16.909 msg: Timeout when waiting for 172.29.236.105:9200
```

Next build: http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-swift-periodic/28/

**Comment by hughsaunders** [comment]
Previous build was killed in unexpected jenkins restart, next build: http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-swift-periodic/29/

**Comment by hughsaunders** [comment]
Failed on second tempest, next build: http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-swift-periodic/32/

**Comment by hughsaunders** [comment]
This will fail check until https://github.com/rcbops/jenkins-rpc/pull/724 merges.

**Comment by hughsaunders** [comment]
Next test run: http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-swift-periodic/49/

**Comment by hughsaunders** [comment]
#724 now merged recheck_all

**Comment by hughsaunders** [comment]
Build after removing unnecessary params: http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-13.1-experimental-ondemand/3/ Build without defcore tests: http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-13.1-experimental-ondemand/4/

**Comment by b3rnard0** [comment]
@dfecker Please add your questions here for @hughsaunders.

**Comment by hughsaunders** [comment]
This is still failing on tempest, though other upgrade jobs are passing. I haven't worked out how this PR could be causing the failure yet.

**Comment by mattt416** [comment]
Created http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-13.1-experimental-ondemand/8/console to troubleshoot this.

**Comment by mattt416** [comment]
I had a poke at this one today, but couldn't find a concrete cause of the tempest failures.  What I do know is that the metadata service is not accessible when an instance boots off the private network.  It looks like there's no neutron-ns-metadata-proxy proc for the private network, meaning if you poke around inside the netns for the private network you cannot see anything bound to port 80.  This appears to be why when the instance boots it cannot reach it.

Why no proc is being spawned (as there is one for the router and the public network) I do not know.  I'll need to spend a bit more time comparing this instance to a working instance to see if I can find a discrepancy.

**Comment by mattt416** [comment]
My test instance got purged, building a new one here:

http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-13.1-experimental-ondemand/10/

**Comment by mattt416** [comment]
So one thing I noticed in http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-13.1-experimental-ondemand/10/ (which failed before even getting to running tempest, which meant persistent resources were left lying about), is that we're boot instances right onto the public network.  While I don't know if this is "supported" behaviour, it does work but makes me wonder if this is perhaps why we're getting the private network in a weird state.

I've created commit https://github.com/mattt416/jenkins-rpc/commit/2bc1b0d3fcca9132efe329825ac44b3ef5b5f39b on my own branch to test.  This basically just spins up some floating IPs, assigns them, and then tests those.  _Hopefully_ this will resolve the tempest (private network) issues we have been seeing.

http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-13.1-experimental-ondemand/11/ if anyone wants to follow along.

**Comment by mattt416** [comment]
Failed as I forgot to boot 2nd instance off private net, created another job here:

http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-13.1-experimental-ondemand/12/console

**Comment by mattt416** [comment]
I spent some more time poking at this yesterday but couldn't pinpoint the problem.  Looks like the last build has been wiped so I'll create another build and see if @Apsu may be able to hop in and have a look.

**Comment by mattt416** [comment]
http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-13.1-experimental-ondemand/14

**Comment by mattt416** [comment]
http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-13.1-experimental-ondemand/18/, since build 15 has since been cleaned up.  :(

**Comment by mattt416** [comment]
A quick update on this.  I made some additional commits in my [fork](https://github.com/mattt416/jenkins-rpc/commit/2bc1b0d3fcca9132efe329825ac44b3ef5b5f39b) to explicitly boot instances on the private network and then attach floating IPs, but this hasn't helped any.  I'm still seeing the same thing -- instances booted on the private network fail to communicate with metadata server.  At first I thought the issue was that there is no metadata proxy running inside the private network's netns (a liberty AIO has one running inside the router ns, the pub and private networks), however this does not seem to be the case on mitaka (only one in the router and one in the pub netns).

I've ensured the AIO still has the port 80 checksum rule in the neutron agents container which I know is needed for this specifically, but still no luck.  I'm sure it's something obvious but someone with more neutron experience will be able to diagnose quicker.

**Comment by b3rnard0** [comment]
Implement as a future feature -- I'll create a new issue for it.

**Pull request closed without merging**
